Add files via upload
Nikssssss/Labs_2.1 pull request #1
Opened 2020-09-21 13:39 UTC by Nikssssss

2020-09-21 13:43 UTC, Nikssssss commented
@Aloomenon

2020-09-24 12:39 UTC, Aloomenon requested changes

2020-09-24 12:39 UTC, Aloomenon commented on Networks_Lab1/src/main/java/App.java
> +                    writer.close();
если на момент закрытия reader читает, а writer пишет, что произойдет?

2020-09-24 13:11 UTC, Nikssssss commented on Networks_Lab1/src/main/java/App.java
> +                    writer.close();
@Aloomenon, вылетает SocketException, постараюсь исправить.

2020-09-24 14:26 UTC, Nikssssss commented on Networks_Lab1/src/main/java/App.java
> +                    writer.close();
@Aloomenon исправил

2020-09-25 13:57 UTC, Aloomenon requested changes

2020-09-25 13:57 UTC, Aloomenon commented on Networks_Lab1/src/main/java/App.java
> +        reader.close();
из хука сюда попадем?

2020-09-28 07:26 UTC, merged